<a href="https://colab.research.google.com/github/Alejandra09MZ/inteligenciaArtificial/blob/main/Lecci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# EJERCICIO 1
import numpy as np
print(np.__version__)


1.25.2
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# EJERCICIO 2
import numpy as np
a = np.arange(10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# EJERCICIO 3
import numpy as np

vector = np.random.randint(0, 100, 10)
print("Vector original:", vector)

indice_maximo = np.argmax(vector)
vector[indice_maximo] = 0
print("Vector modificado:", vector)

Vector original: [44 10  3 18 88  0 96 41 61 72]
Vector modificado: [44 10  3 18 88  0  0 41 61 72]


In [ ]:
# EJERCICIO 4
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 2])

8


In [ ]:
# EJERCICIO 5
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])

[3 4 5]


In [ ]:
# EJERCICIO 6
arr = np.array([1,2,3,4,5,6,7])
print(arr[3:])

[4 5 6 7]


In [ ]:
# EJERCICIO 7
b=np.eye(3,3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# EJERCICIO 8
import numpy as np
a = np.arange(10)
print(a)
impares = a[a % 2 != 0]
print("Números impares son:", impares)

[0 1 2 3 4 5 6 7 8 9]
Números impares son: [1 3 5 7 9]


In [ ]:
# EJERCICIO 9
import numpy as np

vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# EJERCICIO 10
vector = np.arange(10, 50)
print("Vector original:", vector)

primer_elemento = vector[0]
vector = vector[1:]
print(vector)
vector = np.append(vector, primer_elemento)
print("Vector modificado:", vector)

Vector original: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Vector modificado: [11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 10]


In [ ]:
# EJERCICIO 11
import numpy as np
matrix = np.random.rand(10, 10)

max_value = np.max(matrix)
min_value = np.min(matrix)

print("Matriz:")
print(matrix)
print("Valor máximo:", max_value)
print("Valor mínimo:", min_value)

Matriz:
[[8.16167744e-01 3.97538878e-01 5.72126920e-02 3.65255885e-01
  2.30205481e-01 5.40504914e-01 1.43837261e-01 4.57763067e-01
  6.99630683e-01 4.91877024e-01]
 [5.91744244e-01 8.53411340e-01 7.57084319e-02 4.00952263e-01
  4.90429615e-01 3.46009890e-01 6.97866353e-03 7.44354832e-02
  4.50282078e-01 5.20475662e-01]
 [3.52805482e-01 8.84165807e-03 3.33455972e-01 6.62996519e-01
  8.99812180e-01 8.08977212e-02 8.06264173e-01 3.36191577e-01
  9.18376129e-01 5.77740386e-01]
 [8.47570829e-04 8.13170156e-01 6.14037918e-01 2.93192641e-01
  9.27809544e-01 2.02225784e-01 1.44203679e-01 5.22383717e-01
  3.89042917e-01 4.52117036e-01]
 [5.89222243e-01 3.55472979e-01 7.50215441e-01 9.46308588e-01
  5.15756808e-01 8.37654491e-01 8.63317561e-01 3.16887524e-01
  5.33942254e-01 5.94188964e-01]
 [3.29704118e-01 4.85065014e-01 4.00904649e-01 3.11238461e-01
  1.00074707e-01 4.66087831e-02 1.13627196e-01 4.89876488e-02
  2.84136038e-01 7.23898509e-01]
 [1.06173290e-01 8.32655663e-01 4.99272556e-01 7.0

In [ ]:
# EJERCICIO 12
# Create a 3x3x3 array with random values
import numpy as np
matriz_valores_aleatorios = np.random.rand(3, 3, 3)
print(matriz_valores_aleatorios)

[[[0.63699183 0.1708362  0.98188542]
  [0.5942432  0.66440304 0.01896668]
  [0.97477976 0.55137698 0.01571947]]

 [[0.27412682 0.28975379 0.86798473]
  [0.71727137 0.85070947 0.20746581]
  [0.66329993 0.52669447 0.74096617]]

 [[0.25811537 0.62722845 0.60213333]
  [0.22797141 0.82160475 0.44589978]
  [0.35292531 0.29304359 0.94010191]]]


In [ ]:
# EJERCICIO 13
# Replace all odd numbers in arr with -1
arr = np.array([1,2,3,4,5,6,7])
arr[arr % 2 != 0] = -1
print(arr)

[-1  2 -1  4 -1  6 -1]


In [ ]:
# EJERCICIO 14
# Create an array of type float
matriz_float = np.random.rand(3, 3).astype(np.float32)
print(matriz_float)

[[0.494382   0.780589   0.32065332]
 [0.32552186 0.40454006 0.9858608 ]
 [0.848899   0.11098775 0.96277004]]


In [ ]:
# EJERCICIO 15
# Convert a 1D array to a 2D array with 2 rows
arr_1d = np.array([1, 2, 3, 4, 5, 6])
print("Array 1D original:")
print(arr_1d)

arr_2d = arr_1d.reshape(2, -1)
print("Matriz 2D:")
print(arr_2d)

Array 1D original:
[1 2 3 4 5 6]
Matriz 2D:
[[1 2 3]
 [4 5 6]]


In [ ]:
# EJERCICIO 16
# How to find common values between two arrays?
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

valores_comunes = np.intersect1d(Z1, Z2)

print("Matriz Z1:", Z1)
print("Matriz Z2:", Z2)
print("Valores comunes:", valores_comunes)

Matriz Z1: [3 2 4 2 2 2 9 0 3 8]
Matriz Z2: [1 0 3 0 9 9 6 5 0 9]
Valores comunes: [0 3 9]


In [ ]:
# EJERCICIO 17
#  Consider two random array A and B, check if they are equal
# A = np.random.randint(0,2,5)
# B = np.random.randint(0,2,5)

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

son_iguales = np.array_equal(A, B)

print("Matriz A:", A)
print("Matriz B:", B)
print("¿Son iguales?", son_iguales)

Matriz A: [1 0 0 1 0]
Matriz B: [0 1 1 0 1]
¿Son iguales? False


In [ ]:
# EJERCICIO 18
# Stack arrays a and b vertically
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

resultado = np.vstack((A, B))

print(resultado)

[[0 0 0 1 1]
 [0 1 0 0 0]]


In [ ]:
# EJERCICIO 19
# Stack the arrays a and b horizontally
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
resultado = np.hstack((A, B))
print(resultado)

[1 1 0 1 0 0 1 1 1 0]


In [ ]:
# EJERCICIO 20
# Get all items between 5 and 10 from array tmp.
# your code here
import numpy as np
tmp = np.arange(15)
resultado = tmp[(tmp >= 5) & (tmp <= 10)]
print(resultado)

[ 5  6  7  8  9 10]


In [ ]:
# EJERFCICIO 21
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


import numpy as np

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
result = pair_max(a, b)
print(result) # Output: [6 7 9 8 9 7 5]

[6 7 9 8 9 7 5]


In [ ]:
# EJERCICIO 22
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]

arr = np.arange(9).reshape(3,3)
print("Matriz original:")
print(arr)

arr[:, [1, 2]] = arr[:, [2, 1]]
print("Matriz con columnas intercambiadas:")
print(arr)

Matriz original:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Matriz con columnas intercambiadas:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [ ]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

matriz = np.random.uniform(5, 10, size=(5, 3))

print(matriz)

[[5.72780653 7.3593916  5.74260408]
 [6.77850643 7.07430961 8.81400592]
 [5.03678229 9.31064003 5.37864836]
 [7.59667686 9.32735162 7.93500233]
 [5.28227611 9.10726664 5.12285022]]
